version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-data:/data
    environment:
      - EULA=true
      - SERVER_NAME="SVER-DEV's Homelab Minecraft Server"
      - MOTD="Simple homelab minecraft server\u00A7r\nby. \u00A75SVER-DEV"
      - TZ=Asia/seoul
      - DIFFICULTY=EASY
      - VIEW_DISTANCE=10
      - INIT_MEMORY=8G
      - MAX_MEMORY=8G
      - EXEC_DIRECTLY=true
      - TYPE=PAPER
      - JVM_OPTS="--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15"
    labels:
      org.label-schema.group: "homelab_01"
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
    volumes:
      - mc:/data:ro
      - ./mc-backups:/backups
