version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25565:25565 # minecraft
    volumes:
      - ./minecraft-data:/data
    environment:
      - EULA=true
      - TZ=Asia/seoul
      - INIT_MEMORY=8G
      - MAX_MEMORY=8G
      - EXEC_DIRECTLY=true
      - TYPE=PAPER
      - ONLINE_MODE=false # 추후 수정
    labels:
      org.label-schema.group: "homelab_01"
