version: "3.4"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    environment:
      - EULA=true
      - SERVER_NAME="SVER-DEV's Homelab Minecraft Server"
      - MOTD="§f§n벚꽃 서버 | mc.sver.dev   §dCherry blossom"
      - TZ=Asia/seoul
      - DIFFICULTY=EASY
      - VIEW_DISTANCE=10
      - INIT_MEMORY=8G
      - MAX_MEMORY=8G
      - EXEC_DIRECTLY=true
      - TYPE=PAPER
      - ONLINE_MODE=false
      - ENABLE_RCON=true
      - RCON_PASSWORD="homelab01"
      - RCON_PORT=28016
      - SEED=2592193535285114177
      - ENABLE_JMX=true
    labels:
      org.label-schema.group: "homelab_01"
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_PASSWORD: homelab01
      RCON_PORT: 28016
      RCON_HOST: localhost
    volumes:
      - ./minecraft-data:/data:ro
      - ./mc-backups:/backups
